name: build
on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Create manylinux wheels
        with:
          systems-packages: 'net-snmp-devel'
      - name: Create source dist
        run: python setup.py sdist
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
      - name: Add to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
